[workspace]
members = [
    "command_line_tool",
    "pixelmap",
    "cuda"
]

resolver = "2"

# Optionally, you can keep some workspace-level settings:
[profile.release]
lto = true
codegen-units = 10
