[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
description = "Lovely Spam! Wonderful Spam!"

[tool.poetry]
authors = ["Per Brendelökken"]
description ="TOOD"
name ="todo2"
version = "0.1.0"

[tool.poetry.dependencies]
